### ISSUE TITLE
在本机docker中部署unblock，容器内的请求失败

### ISSUE THREAD

**Issue by gaoyang** [wibus-wee/raycast-unblock#103]
### Describe the bug

我使用的QuantumultX配置MitM以及重写

[rewrite_local]
^https:\/\/backend\.raycast\.com .x-raycast-unblock -url-and-header reject-200 （避免循环临时测试用，不起作用）
^https:\/\/backend\.raycast\.com url 302 http://127.0.0.1:3000

启动命令 

docker run -d \
  --name raycast-unblock \
  -e NODE_TLS_REJECT_UNAUTHORIZED=0 \ 
  -p 3000:3000 \
  -v ./config.toml:/app/config.toml \
  wibuswee/raycast-unblock:latest

容器中报错日志
error [Raycast Backend] Request error
{
  request: 'https://backend.raycast.com/api/v1/me',
  options: {
    baseURL: 'https://backend.raycast.com/api/v1',
    headers: Headers {
      'x-raycast-unblock': 'true',
      accept: 'application/json',
      'accept-encoding': 'gzip, deflate, br',
      'accept-language': 'zh-CN,zh-Hans;q=0.9',
      connection: 'keep-alive',
      'content-type': 'application/json',
      host: 'backend.raycast.com',
      'user-agent': 'Raycast/1.76.0 (macOS Version 14.5 (Build 23F79))',
      'x-raycast-signature': '********'
    },
    onRequestError: [Function: onRequestError],
    method: 'GET',
    body: undefined,
    retry: 0
  },
  response: undefined,
  error: TypeError: fetch failed
      at node:internal/deps/undici/undici:12500:13
      at async i (./packages/core/dist/index.js:274:44616)
      at async i (./packages/core/dist/index.js:274:44731)
      at async a (./packages/core/dist/index.js:274:45455)
      at async getBackendResponse (./packages/core/dist/index.js:274:48223)
      at async Me (./packages/core/dist/index.js:274:50420)
      at async Object.<anonymous> (./packages/core/dist/index.js:274:51000) {
    [cause]: SocketError: other side closed
        at TLSSocket.<anonymous> (node:internal/deps/undici/undici:7613:28)
        at TLSSocket.emit (node:events:531:35)
        at endReadableNT (node:internal/streams/readable:1696:12)
        at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
      code: 'UND_ERR_SOCKET',
      socket: [Object]
    }
  }
}
error [GET] /me <-x- Backend Response Error
error FetchError: [GET] "https://backend.raycast.com/api/v1/me": <no response> fetch failed
    at async i (./packages/core/dist/index.js:274:44731)
    ... 3 lines matching cause stack trace ...
    at async Object.<anonymous> (./packages/core/dist/index.js:274:51000) {
  [cause]: TypeError: fetch failed
      at node:internal/deps/undici/undici:12500:13
      at async i (./packages/core/dist/index.js:274:44616)
      at async i (./packages/core/dist/index.js:274:44731)
      at async a (./packages/core/dist/index.js:274:45455)
      at async getBackendResponse (./packages/core/dist/index.js:274:48223)
      at async Me (./packages/core/dist/index.js:274:50420)
      at async Object.<anonymous> (./packages/core/dist/index.js:274:51000) {
    [cause]: SocketError: other side closed
        at TLSSocket.<anonymous> (node:internal/deps/undici/undici:7613:28)
        at TLSSocket.emit (node:events:531:35)
        at endReadableNT (node:internal/streams/readable:1696:12)
        at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
      code: 'UND_ERR_SOCKET',
      socket: [Object]
    }
  }
}

[相关截图]

<img width="570" alt="image" src="https://github.com/wibus-wee/raycast-unblock/assets/21971650/387cc2f0-371d-4746-8642-d11c6cc10616">

<img width="478" alt="image" src="https://github.com/wibus-wee/raycast-unblock/assets/21971650/13eb63a5-2123-48cd-82ce-c24e4826b180">

### Reproduction

macOS

### System Info

```Shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M2
    Memory: 73.39 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.2.0 - ~/.nvm/versions/node/v22.2.0/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v22.2.0/bin/npm
    pnpm: 9.2.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Safari: 17.5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wibus-wee** [comment]
🧐 我并没有试过 QuantumultX，可能你需要检索一下 `UND_ERR_SOCKET` 和 `[cause]: SocketError: other side closed` 会出现的原因。这在之前出现类似问题的时候都没有出现过的 error message

**Comment by gaoyang** [comment]
应该是 QuantumultX 关闭了连接导致，UnBlock 使用 Surge 本地 docker 部署可以运行吗？

**Comment by wibus-wee** [comment]
文档里已经说明了
