### ISSUE TITLE
请问下正常docker部署报这个错误是什么原因

### ISSUE THREAD

**Issue by panthole** [wibus-wee/raycast-unblock#73]
### Describe the bug

![WeChat364770054b43a09aaf4eb5f3ccbf7432](https://github.com/wibus-wee/raycast-unblock/assets/4142451/a5b6cc8a-ef7d-4200-94c1-11c0ae79d5f9)

### Reproduction

docker部署mitnproxy配置

### System Info

```Shell
info [DEBUG]  [GET] /me <-- Backend Response
{
  request: 'https://backend.raycast.com/api/v1/me',

  options: {
    baseURL: 'https://backend.raycast.com/api/v1',
    headers: Headers {
      'x-raycast-unblock': 'true',
      accept: 'application/json',
      'accept-encoding': 'gzip, deflate, br',
      'accept-language': 'zh-CN,zh-Hans;q=0.9',
      authorization: 'Bearer JylPgzUpSyUIKDzKMH6N_LM1h3k6JV5yEtPdQ60-7xo',
      'content-type': 'application/json',
      host: 'backend.raycast.com',
      'user-agent': 'Raycast/1.72.1 (macOS Version 14.3.1 (Build 23D60))',
      'x-forwarded-for': '101.224.149.99',
      'x-forwarded-proto': 'https',
      'x-forwarded-scheme': 'https',
      'x-raycast-signature': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhaWQiOiI0ODA1MTc2OS0xODRDLTQwMTQtQkM5RC04QkRFMkY3MkQ0NEUiLCJleHAiOjE3MTQ3NDQwOTUuMjE1NTU5LCJpYXQiOjE3MTQ3NDQwMzUuMjE1NTU5fQ.NiD8USEgl0nCzLhYRBMaqzsnvaEvh2RPeSDJSFkxXLg',
      'x-real-ip': '101.224.149.99'
    },
    onRequestError: [Function: onRequestError],
    method: 'GET',
    body: undefined,
    retry: 0,
    timeout: undefined
  },
  response: undefined,
  error: TypeError: fetch failed
      at node:internal/deps/undici/undici:12500:13
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async o (dist/index.js:48:538322)
      at async o (dist/index.js:48:538437)
      at async a (dist/index.js:48:539237)
      at async vse (dist/index.js:248:33234)
      at async dist/index.js:248:34849
      at async Object.<anonymous> (dist/index.js:248:34818) {
    [cause]: Error: read ECONNRESET
        at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
        at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
      errno: -104,
      code: 'ECONNRESET',
      syscall: 'read'
    }
  }
}
error [Raycast Backend] Request error
error [GET] /me <-x- Backend Response Error
error aY [FetchError]: [GET] "https://backend.raycast.com/api/v1/me": <no response> fetch failed
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async o (dist/index.js:48:538437)
    ... 3 lines matching cause stack trace ...
    at async Object.<anonymous> (dist/index.js:248:34818) {
  [cause]: TypeError: fetch failed
      at node:internal/deps/undici/undici:12500:13
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async o (dist/index.js:48:538322)
      at async o (dist/index.js:48:538437)
      at async a (dist/index.js:48:539237)
      at async vse (dist/index.js:248:33234)
      at async dist/index.js:248:34849
      at async Object.<anonymous> (dist/index.js:248:34818) {
    [cause]: Error: read ECONNRESET
        at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
        at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
      errno: -104,
      code: 'ECONNRESET',
      syscall: 'read'
    }
  }
}
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wibus-wee** [comment]
你确定你的docker容器可以正常访问 backend.raycast.com 吗？

**Comment by panthole** [comment]
![image](https://github.com/wibus-wee/raycast-unblock/assets/4142451/19ca48db-f5c0-4ad5-9d2f-8f0ce258c9ec)
这个是启动时候的日志curl 3000也可以正常返回

**Comment by panthole** [comment]
![image](https://github.com/wibus-wee/raycast-unblock/assets/4142451/9fa595c9-f81a-40b1-95a2-05bc19175997)
这个是启动时候的日志，curl 3000可以正常返回

**Comment by wibus-wee** [comment]
就是平替掉的，但是你也要保留docker能正常访问回官方的 backend 😂 只是运行 raycast 的机器访问 backend.rayxxxx 的时候需要拦截到自建的 unblock 中去

因为raycast unblock需要访问官方后端获取用户信息，这些信息会被用来在raycast unblock中区分不同的用户

**Comment by wibus-wee** [comment]
了解👌后续做一下

**Comment by wibus-wee** [comment]
如果有可能的话

你可以通过 header 中是否存在 x-raycast-unblock 进行判断是raycast发出的请求还是unblock发出的请求

从而让unblock正常访问

**Comment by panthole** [comment]
好的，谢谢
