### ISSUE TITLE
The backend fails to run after version 1.74.1

### ISSUE THREAD

**Issue by CNSCSQ** [wibus-wee/raycast-unblock#87]
### Describe the bug

The latest version of DockerHub I use, the following error occurred after the new version software automatic update
```
error [GET] /me <-x- Backend Response Error
error FetchError: [GET] "https://backend.raycast.com/api/v1/me": <no response> fetch failed
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async i (./packages/core/dist/index.js:274:44731)
    ... 3 lines matching cause stack trace ...
    at async Object.<anonymous> (./packages/core/dist/index.js:274:51000) {
  [cause]: TypeError: fetch failed
      at node:internal/deps/undici/undici:12500:13
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async i (./packages/core/dist/index.js:274:44616)
      at async i (./packages/core/dist/index.js:274:44731)
      at async a (./packages/core/dist/index.js:274:45455)
      at async getBackendResponse (./packages/core/dist/index.js:274:48223)
      at async Me (./packages/core/dist/index.js:274:50420)
      at async Object.<anonymous> (./packages/core/dist/index.js:274:51000) {
    [cause]: Error: getaddrinfo EAI_AGAIN backend.raycast.com
        at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)
        at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
      errno: -3001,
      code: 'EAI_AGAIN',
      syscall: 'getaddrinfo',
      hostname: 'backend.raycast.com'
    }
  }
}
```
I don't know if it's my setting problem, the data of the software should have correctly forwarded to the backend, is this my individual case?

I can provide full log if needed.
<img width="1112" alt="image" src="https://github.com/wibus-wee/raycast-unblock/assets/40529518/9f6d3383-5bba-419e-932d-f71d3b74654e">

### Reproduction

Upgrade to 1.74.1

### System Info

```Shell
Raycast/1.74.1 (macOS Version 14.4.1 (Build 23E224))
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wibus-wee** [comment]
It seems unrelated to raycasting. This is a request error, and you might need to check your container DNS settings?

**Comment by CNSCSQ** [comment]
> 它似乎与光线投射无关。 这是请求错误，您可能需要检查您的容器 DNS 设置？
是的，是我的容器设置问题surge的VIF模式和orbstack的DNS有严重的兼容性问题，我为此困扰了很久，我应该在出现这个问题的时候先询问下ChatGPT的，对不起给您造成麻烦了，谢谢您的回答！我已经通过设置解决了这个问题。

**Comment by CNSCSQ** [comment]
> 它似乎与光线投射无关。 这是请求错误，您可能需要检查您的容器 DNS 设置？

是的，是我的容器设置问题surge的VIF模式和orbstack的DNS有严重的兼容性问题，我为此困扰了很久，我应该在出现这个问题的时候先询问下ChatGPT的，对不起给您造成麻烦了，谢谢您的回答！我已经通过设置解决了这个问题。
